apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-mern-app
  labels:
    name: registration-mern-app
    type: front-end
spec:
  template:
    metadata:
      name: registration-mern-app
      labels:
        name: registration-mern-app
        type: front-end
    spec:
      containers:
        - name: registration-mern-app-cont
          image: vootlasaicharan/registration-mern
          ports:
            - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      type: front-end