apiVersion: v1
kind: Service
metadata:
  name: registration-mern-app
  labels:
    name: registration-mern-app
    type: front-end
spec:
  type: NodePort
  selector:
    type: front-end
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004